export const DEFAULT_CIRCUIT_PLACE_RADIUS_METERS = 10_000;
export const MAX_CIRCUIT_PLACE_RADIUS_METERS = 20_000;
export const DEFAULT_CIRCUIT_PLACE_LIMIT = 100;
export const MAX_CIRCUIT_PLACE_LIMIT = 250;
